import "./globals.css";
import Link from "next/link"; // import the Link component from Next.js

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Users App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/users">Users Page</Link>
            </li>
          </ul>
        </nav>
        <div className="children-container"> {children}</div>
      </body>
    </html>
  );
}
